### ISSUE TITLE
Do you have scratches in decomp.me?

### ISSUE THREAD

**Issue by GermanAizek** [happyhavoc/th06#221]
Community can help with decompilation if you put your scratches there.
More info: https://decomp.me/

**Comment by roblabla** [comment]
You can generate decomp.me scratches with [`generate_function_decompme.py`](https://github.com/happyhavoc/th06/blob/master/scripts/generate_function_decompme.py). Unfortunately, I kinda gave up on decomp.me because of how completely buggy asm-differ is on x86, making a lot of functions just not work in decomp.me. Here's an example: https://decomp.me/scratch/EKPbk . I tried to improve it, but I think asm-differ's regex-based approach is just fundamentally flawed, and I'm not interested in chasing bugs in it.

So instead I now use objdiff, which requires a local setup. It's a bit finicky currently (it was just merged into th06 yesterday, and not properly documented yet), but at least objdiff is much more reliably and built on a much more solid foundation.

There is an integration of objdiff into decomp.me as an alternative differ (you can enable it in your decomp.me profile settings, at the end of the editor category), but it doesn't seem to work for some reason either - with no error to boot. I should probably ask around the decomp.me about that one.

**Comment by roblabla** [comment]
Yeah after checking in, it looks like the objdiff decomp.me integration is still in the very early days and has a lot of stuff missing. It's mostly merged to help development and avoid bitrot, but it's not ready to use.

When this gets fixed, I might look into automating the generation of scratches for all stubbed functions.
